-d D:\fpga\proj\fpga_project\impl\gwsynthesis\fpga_project.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst D:\fpga\proj\fpga_project\src\fpga_project.cst
-cfg D:\fpga\proj\fpga_project\impl\pnr\device.cfg
-sdc D:\fpga\proj\fpga_project\src\fpga_project.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
